### ISSUE TITLE
problems: the step of ./install-soci

### ISSUE THREAD

**Issue by QiangXiao-Ch** [dipterix/arm-rstudio-server#2]
although, i reinstall sqlite 3，

sudo apt install sqlite3

then go to /opt/rstudio-tools/，see no soci

then run ./install-soci , it return: sudo: curl: command not found

**Comment by QiangXiao-Ch** [comment]
OK， problem was solved，reinstall the curl，sudo apt install curl

**Comment by dipterix** [comment]
Great, glad you figured it out!
